### ISSUE TITLE
missing style sheet?

### ISSUE THREAD

**Issue by mrneilypops** [if-Team/origami#2]
![screenshot from 2017-02-26 19-30-25](https://cloud.githubusercontent.com/assets/1450448/23342410/1c9a94d4-fc5a-11e6-8653-b6c576aa9e78.png)
Hi,
Love the theme!
I have tried to install the theme on different platforms...digital ocean/exoscale/ghost pro.
On all platforms I just a get a page that appears to be missing style sheets.
Am i missing something?

**Comment by seompark** [comment]
Did you build it with webpack? you must build this project before applying this theme on your Ghost.

## How?
Just clone this repository into theme path, and build.

Follow commands :
```
$ git clone https://github.com/if-Team/origami && cd origami
$ npm install
$ npm run build --production
```
If you already cloned or downloaded it, just type last two commands.

There is the other simple solution that download releases in this repository built, but, however,  it's not up-to-date.

**Comment by mrneilypops** [comment]
`mrneilypops@nejulinux:/var/www/nejulinux.org/content/themes/origami$ sudo npm install
mrneilypops@nejulinux:/var/www/nejulinux.org/content/themes/origami$ sudo npm run build --production

> origami@1.3.0 build /var/www/nejulinux.org/content/themes/origami
> webpack

loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Killed

npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build" "--production"
npm ERR! node v4.7.3
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! origami@1.3.0 build: `webpack`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the origami@1.3.0 build script 'webpack'.
npm ERR! This is most likely a problem with the origami package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs origami
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls origami
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/nejulinux.org/content/themes/origami/npm-debug.log
mrneilypops@nejulinux:/var/www/nejulinux.org/content/themes/origami$ 
'
npm-debug.log

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--production' ]
2 info using npm@2.15.11
3 info using node@v4.7.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild origami@1.3.0
6 info build origami@1.3.0
7 verbose unsafe-perm in lifecycle true
8 info origami@1.3.0 Failed to exec build script
9 verbose stack Error: origami@1.3.0 build: `webpack`
9 verbose stack Exit status 137
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:854:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
10 verbose pkgid origami@1.3.0
11 verbose cwd /var/www/nejulinux.org/content/themes/origami
12 error Linux 4.4.0-64-generic
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build" "--production"
14 error node v4.7.3
15 error npm  v2.15.11
16 error code ELIFECYCLE
17 error origami@1.3.0 build: `webpack`
17 error Exit status 137
18 error Failed at the origami@1.3.0 build script 'webpack'.
18 error This is most likely a problem with the origami package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     webpack
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs origami
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls origami
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]`

**Comment by seompark** [comment]
Sorry, We'll fix ASAP.

**Comment by mrneilypops** [comment]
No worries...I really like your work...great theme...looking forward to using it!

**Comment by seompark** [comment]
Thx!
By the way, as you know I'm not a developer of origami. It's @HelloWorld017

**Comment by HelloWorld017** [comment]
```
loaderUtils.parseQuery() received a non-string value which can be problematic, see webpack/loader-utils#56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```
are just warnings.

You can skip it.
Or, if you want to use built things, you can download it from releases tab.
(It contains assets directory which contains stylesheets / javascript / fonts)

Thank you for using origami!

**Comment by mrneilypops** [comment]
Hi,

Great work team!

Origami theme up and running at;

https://mrneilypops.io

Thank you.

Neil

**Comment by HelloWorld017** [comment]
It's glad to hear that theme has been built successfully!

Thank you for using origami!
