### ISSUE TITLE
No post??

### ISSUE THREAD

**Issue by KeyLD** [if-Team/origami#4]
Hi there,

love your theme.
But it seems that some error occured.

![](http://i2.muimg.com/567571/a551d0734fdf8762.jpg)

What happened???
In fact,There are some posts on my blog.

Besides, I failed to install it by git so I downloaded Origami-1.3.0.zip.

**Comment by seompark** [comment]
Did you check 'Public API' option? It's required

**Comment by KeyLD** [comment]
Hey! It works!!!
The theme is so fansy! I like it!
Thank you.
