### ISSUE TITLE
Font does not support cyrillic charactes

### ISSUE THREAD

**Issue by W1nterSilence** [if-Team/origami#5]
Hi! 

I really like your theme, but I noticed that the font you use does not support Cyrillic characters - when you try to type in Russian, the font gets substituted with the ugly arial bold and it ruins all the style.

Maybe there is a way to include the Cyrillic characters to the font?

**Comment by Flaplim** [comment]
@W1nterSilence .

**Comment by HelloWorld017** [comment]
# Please find a font.
 * Please enter fonts.google.com and find a font which supports Cyrillic characters.
When I googled for it, I noticed that PT Sans and some other fonts suppirts Cyrillic characters.
* Please select fonts you like and press red plus-shaped button and click `(number) Family selected`.

Then, you'll find a text like
```
<link href="https://fonts.googleapis.com/css?family=blahblah" rel="stylesheet">
```
Please copy the text.
Also, please remember `Specify in CSS`
```
font-family: 'Roboto', sans-serif;
font-family: 'Open Sans', sans-serif;
```

If things are like this, you may need the font name next to the `font-family: `

# Please go to the ghost setting.
Please click code injection
In `Blog Header` section, please paste your text. 

And please paste this to:
```
<style>
.site-footer, .pagination, .page-number,
h1, h2, h3, h4, h5, h6, button,
.main-nav a, .nav-title, .nav-link span,
.subscribe-button, .page-title {
	font-family: 'Title font here', sans-serif;
}

.gh-subscribe-rss,
body, textarea, select, input,
.nav-desc, .page-description,
.post-meta, 
.author-profile .author-meta,
.read-next-story .post:before {
	font-family: 'Content font here', sans-serif;
}
</style>
```
Now, change the `Title font here` and `Content font here` to the font name you wants.

If you also want to change code fonts, please add
```
code, tt, pre, kbd, samp {
	font-family: 'Code font here', sans-serif;
}
```
and change `Code font here` to the font name you wants.

Thank you for using Origami!!
