### ISSUE TITLE
Disqus installation

### ISSUE THREAD

**Issue by W1nterSilence** [if-Team/origami#6]
Hi again,

Sorry for bothering you with my lame question, but I have one more. I want to add comment engine to my blog. I've chose Disqus, and it have rather clear instructions for the installation [here](https://disqus.com/admin/install/platforms/universalcode). I've managed to add the code of the Disqus thread in the post.hbs, but I can't find out how to add comment counter for posts on the main page - could you please advice if it is possible?

**Comment by HelloWorld017** [comment]
1. Please clone this repository and install node.js.
2. Please execute `npm install` in project root directory.
3. Please edit src/components/Post.vue.
`<h2 class="post-title"><a :href="url">{{title}}</a></h2>`
to
`<h2 class="post-title"><a :href="url + "#disqus_thread">{{title}}</a></h2>`
4. Please execute `npm build --production` in project root directory and copy js and css files in dist folder.
5. Please add `<script id="dsq-count-scr" src="//EXAMPLE.disqus.com/count.js" async></script>` in code injection.

Thank you!
