### ISSUE TITLE
Origami does not function when Ghost is installed as a subfolder

### ISSUE THREAD

**Issue by Nihlus** [if-Team/origami#7]
I've got Ghost installed at www.mysite.com/blog instead of having it at the root url. However, Origami does not recognize this in the post carding, and instead points to the root url, omitting the subfolder.  This results in incorrect and broken links.

I'm using Origami 1.3.0.

**Comment by HelloWorld017** [comment]
Did you edit url in config.js of Ghost and enabled experimental api?

**Comment by Nihlus** [comment]
Yes. I'm running Ghost under Apache, if that makes a difference.

**Comment by HelloWorld017** [comment]
Could you tell me what links are broken?
ex) Post link or image link, etc ....

**Comment by Nihlus** [comment]
It's all links which are generated through JavaScript - primarily in the post carding on the main page. Read More, tag links, author links and so on. You can still manually navigate to the post and there everything works as expected. 

You can view a live demonstration of the problem here: http://sharkman.asuscomm.com/blog/

**Comment by HelloWorld017** [comment]
Thank you! I'll fix it as soon as possible.

**Comment by Nihlus** [comment]
Awesome :D
