### ISSUE TITLE
Add submodule init command to the README

### ISSUE THREAD

**Issue by snaiperskaya96** [if-Team/origami#8]
You need to `git submodule init` right before updating the submodules otherwise nothing will happen and the theme won't work properly

**Comment by snaiperskaya96** [comment]
Also the Nanum Square repo doesn't exist anymore. I'm using https://github.com/hiun/NanumSquare.git instead but i'm not even sure if it's the same thing

**Comment by HelloWorld017** [comment]
Thank you for reporting this! Fixed on a8b0fa .
