### ISSUE TITLE
Progress on 2.0.0

### ISSUE THREAD

**Issue by TheYorkshireDev** [if-Team/origami#9]
I see that last summer there was an attempt to work on Origami v2, I was wondering where this work stands going forward to fully support Ghost 1.0.

Thanks, great theme.

**Comment by HelloWorld017** [comment]
2.0.2-beta might work on Ghost 1.x!

**Comment by TheYorkshireDev** [comment]
@HelloWorld017 Do you plan to continue work on the theme for 1.x? and will you accept pull requests?

**Comment by HelloWorld017** [comment]
Merged #10!
